### ISSUE TITLE
Checklist for v2.20.0 Release

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1360]
- [x] All items should be closed in [milestone](https://github.com/dotnet/Open-XML-SDK/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.20.0)
- [x] CHANGELOG updated
  - [x] @twsouthwick (#1363)
  - [x] @tomjebo 
  - [x] @mikeebowen 
- [x] Identify build to tag [up-for-grabs]
- [x] Final build tagged and built
- [x] Pushed to NuGet
